// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addGroupContextMessage = `-- name: AddGroupContextMessage :exec
INSERT INTO group_context_messages (group_id, role, text) VALUES ($1, $2, $3)
`

type AddGroupContextMessageParams struct {
	GroupID int64  `json:"group_id"`
	Role    string `json:"role"`
	Text    string `json:"text"`
}

func (q *Queries) AddGroupContextMessage(ctx context.Context, arg AddGroupContextMessageParams) error {
	_, err := q.db.Exec(ctx, addGroupContextMessage, arg.GroupID, arg.Role, arg.Text)
	return err
}

const countGroupContextMessages = `-- name: CountGroupContextMessages :one
SELECT COUNT(*) FROM group_context_messages WHERE group_id = $1
`

func (q *Queries) CountGroupContextMessages(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupContextMessages, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (telegram_id, group_username, group_name)
VALUES ($1, $2, $3)
RETURNING id, telegram_id, balance, group_username, group_name, premium_until, last_interaction, thread_id, selected_model, show_cost, context_enabled, created_at, updated_at
`

type CreateGroupParams struct {
	TelegramID    int64  `json:"telegram_id"`
	GroupUsername string `json:"group_username"`
	GroupName     string `json:"group_name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.TelegramID, arg.GroupUsername, arg.GroupName)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Balance,
		&i.GroupUsername,
		&i.GroupName,
		&i.PremiumUntil,
		&i.LastInteraction,
		&i.ThreadID,
		&i.SelectedModel,
		&i.ShowCost,
		&i.ContextEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupContextMessages = `-- name: DeleteGroupContextMessages :exec
DELETE FROM group_context_messages WHERE group_id = $1
`

func (q *Queries) DeleteGroupContextMessages(ctx context.Context, groupID int64) error {
	_, err := q.db.Exec(ctx, deleteGroupContextMessages, groupID)
	return err
}

const deleteOldestGroupContextMessages = `-- name: DeleteOldestGroupContextMessages :exec
DELETE FROM group_context_messages
WHERE id IN (
    SELECT gcm.id FROM group_context_messages gcm
    WHERE gcm.group_id = $1
    ORDER BY gcm.created_at ASC
    LIMIT $2
)
`

type DeleteOldestGroupContextMessagesParams struct {
	GroupID int64 `json:"group_id"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) DeleteOldestGroupContextMessages(ctx context.Context, arg DeleteOldestGroupContextMessagesParams) error {
	_, err := q.db.Exec(ctx, deleteOldestGroupContextMessages, arg.GroupID, arg.Limit)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, telegram_id, balance, group_username, group_name, premium_until, last_interaction, thread_id, selected_model, show_cost, context_enabled, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Balance,
		&i.GroupUsername,
		&i.GroupName,
		&i.PremiumUntil,
		&i.LastInteraction,
		&i.ThreadID,
		&i.SelectedModel,
		&i.ShowCost,
		&i.ContextEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByTelegramID = `-- name: GetGroupByTelegramID :one
SELECT id, telegram_id, balance, group_username, group_name, premium_until, last_interaction, thread_id, selected_model, show_cost, context_enabled, created_at, updated_at FROM groups WHERE telegram_id = $1
`

func (q *Queries) GetGroupByTelegramID(ctx context.Context, telegramID int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByTelegramID, telegramID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Balance,
		&i.GroupUsername,
		&i.GroupName,
		&i.PremiumUntil,
		&i.LastInteraction,
		&i.ThreadID,
		&i.SelectedModel,
		&i.ShowCost,
		&i.ContextEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupContextMessages = `-- name: GetGroupContextMessages :many
SELECT id, group_id, role, text, created_at FROM group_context_messages WHERE group_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetGroupContextMessages(ctx context.Context, groupID int64) ([]GroupContextMessage, error) {
	rows, err := q.db.Query(ctx, getGroupContextMessages, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupContextMessage{}
	for rows.Next() {
		var i GroupContextMessage
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Role,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupForUpdate = `-- name: GetGroupForUpdate :one
SELECT id, telegram_id, balance, group_username, group_name, premium_until, last_interaction, thread_id, selected_model, show_cost, context_enabled, created_at, updated_at FROM groups WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetGroupForUpdate(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupForUpdate, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Balance,
		&i.GroupUsername,
		&i.GroupName,
		&i.PremiumUntil,
		&i.LastInteraction,
		&i.ThreadID,
		&i.SelectedModel,
		&i.ShowCost,
		&i.ContextEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGroupPremiumUntil = `-- name: SetGroupPremiumUntil :exec
UPDATE groups SET premium_until = $2, updated_at = NOW() WHERE id = $1
`

type SetGroupPremiumUntilParams struct {
	ID           int64              `json:"id"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
}

func (q *Queries) SetGroupPremiumUntil(ctx context.Context, arg SetGroupPremiumUntilParams) error {
	_, err := q.db.Exec(ctx, setGroupPremiumUntil, arg.ID, arg.PremiumUntil)
	return err
}

const setGroupSelectedModel = `-- name: SetGroupSelectedModel :exec
UPDATE groups SET selected_model = $2, updated_at = NOW() WHERE id = $1
`

type SetGroupSelectedModelParams struct {
	ID            int64  `json:"id"`
	SelectedModel string `json:"selected_model"`
}

func (q *Queries) SetGroupSelectedModel(ctx context.Context, arg SetGroupSelectedModelParams) error {
	_, err := q.db.Exec(ctx, setGroupSelectedModel, arg.ID, arg.SelectedModel)
	return err
}

const setGroupThreadID = `-- name: SetGroupThreadID :exec
UPDATE groups SET thread_id = $2, updated_at = NOW() WHERE id = $1
`

type SetGroupThreadIDParams struct {
	ID       int64  `json:"id"`
	ThreadID *int32 `json:"thread_id"`
}

func (q *Queries) SetGroupThreadID(ctx context.Context, arg SetGroupThreadIDParams) error {
	_, err := q.db.Exec(ctx, setGroupThreadID, arg.ID, arg.ThreadID)
	return err
}

const toggleGroupContextEnabled = `-- name: ToggleGroupContextEnabled :exec
UPDATE groups SET context_enabled = NOT context_enabled, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ToggleGroupContextEnabled(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleGroupContextEnabled, id)
	return err
}

const toggleGroupShowCost = `-- name: ToggleGroupShowCost :exec
UPDATE groups SET show_cost = NOT show_cost, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ToggleGroupShowCost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleGroupShowCost, id)
	return err
}

const updateGroupBalance = `-- name: UpdateGroupBalance :one
UPDATE groups SET balance = balance + $2, updated_at = NOW() WHERE id = $1
RETURNING balance
`

type UpdateGroupBalanceParams struct {
	ID      int64           `json:"id"`
	Balance decimal.Decimal `json:"balance"`
}

func (q *Queries) UpdateGroupBalance(ctx context.Context, arg UpdateGroupBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, updateGroupBalance, arg.ID, arg.Balance)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const updateGroupBalanceWithCheck = `-- name: UpdateGroupBalanceWithCheck :one
UPDATE groups SET balance = balance + $2, updated_at = NOW()
WHERE id = $1 AND balance + $2 >= 0
RETURNING balance
`

type UpdateGroupBalanceWithCheckParams struct {
	ID      int64           `json:"id"`
	Balance decimal.Decimal `json:"balance"`
}

func (q *Queries) UpdateGroupBalanceWithCheck(ctx context.Context, arg UpdateGroupBalanceWithCheckParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, updateGroupBalanceWithCheck, arg.ID, arg.Balance)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const updateGroupInfo = `-- name: UpdateGroupInfo :exec
UPDATE groups SET group_username = $2, group_name = $3, updated_at = NOW() WHERE id = $1
`

type UpdateGroupInfoParams struct {
	ID            int64  `json:"id"`
	GroupUsername string `json:"group_username"`
	GroupName     string `json:"group_name"`
}

func (q *Queries) UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) error {
	_, err := q.db.Exec(ctx, updateGroupInfo, arg.ID, arg.GroupUsername, arg.GroupName)
	return err
}

const updateGroupLastInteraction = `-- name: UpdateGroupLastInteraction :exec
UPDATE groups SET last_interaction = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateGroupLastInteraction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateGroupLastInteraction, id)
	return err
}
