// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (user_telegram_id, amount, cryptomus_invoice_id)
VALUES ($1, $2, $3)
RETURNING id, user_telegram_id, amount, cryptomus_invoice_id, status, created_at
`

type CreateInvoiceParams struct {
	UserTelegramID     int64           `json:"user_telegram_id"`
	Amount             decimal.Decimal `json:"amount"`
	CryptomusInvoiceID string          `json:"cryptomus_invoice_id"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice, arg.UserTelegramID, arg.Amount, arg.CryptomusInvoiceID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserTelegramID,
		&i.Amount,
		&i.CryptomusInvoiceID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoiceByCryptomusID = `-- name: GetInvoiceByCryptomusID :one
SELECT id, user_telegram_id, amount, cryptomus_invoice_id, status, created_at FROM invoices WHERE cryptomus_invoice_id = $1
`

func (q *Queries) GetInvoiceByCryptomusID(ctx context.Context, cryptomusInvoiceID string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByCryptomusID, cryptomusInvoiceID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserTelegramID,
		&i.Amount,
		&i.CryptomusInvoiceID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvoiceByUser = `-- name: GetPendingInvoiceByUser :one
SELECT id, user_telegram_id, amount, cryptomus_invoice_id, status, created_at FROM invoices
WHERE user_telegram_id = $1 AND status = 'pending' AND created_at > NOW() - INTERVAL '30 minutes'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingInvoiceByUser(ctx context.Context, userTelegramID int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getPendingInvoiceByUser, userTelegramID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.UserTelegramID,
		&i.Amount,
		&i.CryptomusInvoiceID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = $2 WHERE id = $1
`

type UpdateInvoiceStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	return err
}
