// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type ActiveRequest struct {
	ChatID    int64              `json:"chat_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

type ChatSession struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Model       string             `json:"model"`
	Temperature decimal.Decimal    `json:"temperature"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID              int64              `json:"id"`
	TelegramID      int64              `json:"telegram_id"`
	Balance         decimal.Decimal    `json:"balance"`
	GroupUsername   string             `json:"group_username"`
	GroupName       string             `json:"group_name"`
	PremiumUntil    pgtype.Timestamptz `json:"premium_until"`
	LastInteraction pgtype.Timestamptz `json:"last_interaction"`
	ThreadID        *int32             `json:"thread_id"`
	SelectedModel   string             `json:"selected_model"`
	ShowCost        bool               `json:"show_cost"`
	ContextEnabled  bool               `json:"context_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GroupContextMessage struct {
	ID        int64              `json:"id"`
	GroupID   int64              `json:"group_id"`
	Role      string             `json:"role"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID                 int64              `json:"id"`
	UserTelegramID     int64              `json:"user_telegram_id"`
	Amount             decimal.Decimal    `json:"amount"`
	CryptomusInvoiceID string             `json:"cryptomus_invoice_id"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type MessageFile struct {
	ID        int64  `json:"id"`
	MessageID int64  `json:"message_id"`
	FileType  string `json:"file_type"`
	Url       string `json:"url"`
	Name      string `json:"name"`
}

type PayTask struct {
	ID           int64              `json:"id"`
	Title        string             `json:"title"`
	TelegramLink string             `json:"telegram_link"`
	ChannelID    string             `json:"channel_id"`
	Reward       decimal.Decimal    `json:"reward"`
	TimeLimit    pgtype.Timestamptz `json:"time_limit"`
	MaxPeople    *int32             `json:"max_people"`
}

type PayTaskCompletion struct {
	ID          int64              `json:"id"`
	TaskID      int64              `json:"task_id"`
	UserID      int64              `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Promo struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Amount    decimal.Decimal    `json:"amount"`
	Comment   string             `json:"comment"`
	MaxUses   int32              `json:"max_uses"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PromoActivation struct {
	ID          int64              `json:"id"`
	PromoID     int64              `json:"promo_id"`
	UserID      int64              `json:"user_id"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
}

type Prompt struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PromptText  string             `json:"prompt_text"`
	IsOfficial  bool               `json:"is_official"`
	OwnerID     *int64             `json:"owner_id"`
	Price       decimal.Decimal    `json:"price"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RateLimit struct {
	ChatID       int64              `json:"chat_id"`
	RequestCount int32              `json:"request_count"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
}

type SessionMessage struct {
	ID        int64              `json:"id"`
	SessionID int64              `json:"session_id"`
	Role      string             `json:"role"`
	Text      string             `json:"text"`
	Images    []string           `json:"images"`
	IsSystem  bool               `json:"is_system"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID          int64              `json:"id"`
	UserID      *int64             `json:"user_id"`
	GroupID     *int64             `json:"group_id"`
	Amount      decimal.Decimal    `json:"amount"`
	TxType      string             `json:"tx_type"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               int64              `json:"id"`
	TelegramID       int64              `json:"telegram_id"`
	IsAdmin          bool               `json:"is_admin"`
	FirstName        string             `json:"first_name"`
	Username         string             `json:"username"`
	Balance          decimal.Decimal    `json:"balance"`
	ReferralCode     string             `json:"referral_code"`
	ReferralBalance  decimal.Decimal    `json:"referral_balance"`
	ReferredByID     *int64             `json:"referred_by_id"`
	PremiumUntil     pgtype.Timestamptz `json:"premium_until"`
	ActiveSessionID  *int64             `json:"active_session_id"`
	LastInteraction  pgtype.Timestamptz `json:"last_interaction"`
	SelectedModel    string             `json:"selected_model"`
	FavoriteModels   []string           `json:"favorite_models"`
	Temperature      decimal.Decimal    `json:"temperature"`
	ShowCost         bool               `json:"show_cost"`
	SendUserInfo     bool               `json:"send_user_info"`
	ContextEnabled   bool               `json:"context_enabled"`
	SessionTimeoutMs int32              `json:"session_timeout_ms"`
	LastSkysmart     pgtype.Timestamptz `json:"last_skysmart"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
