// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const checkPromoActivation = `-- name: CheckPromoActivation :one
SELECT EXISTS(
    SELECT 1 FROM promo_activations WHERE promo_id = $1 AND user_id = $2
) AS activated
`

type CheckPromoActivationParams struct {
	PromoID int64 `json:"promo_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CheckPromoActivation(ctx context.Context, arg CheckPromoActivationParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPromoActivation, arg.PromoID, arg.UserID)
	var activated bool
	err := row.Scan(&activated)
	return activated, err
}

const countPromoActivations = `-- name: CountPromoActivations :one
SELECT COUNT(*) FROM promo_activations
`

func (q *Queries) CountPromoActivations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPromoActivations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromos = `-- name: CountPromos :one
SELECT COUNT(*) FROM promos
`

func (q *Queries) CountPromos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPromos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromo = `-- name: CreatePromo :one
INSERT INTO promos (code, amount, comment, max_uses, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, amount, comment, max_uses, created_by, created_at
`

type CreatePromoParams struct {
	Code      string          `json:"code"`
	Amount    decimal.Decimal `json:"amount"`
	Comment   string          `json:"comment"`
	MaxUses   int32           `json:"max_uses"`
	CreatedBy int64           `json:"created_by"`
}

func (q *Queries) CreatePromo(ctx context.Context, arg CreatePromoParams) (Promo, error) {
	row := q.db.QueryRow(ctx, createPromo,
		arg.Code,
		arg.Amount,
		arg.Comment,
		arg.MaxUses,
		arg.CreatedBy,
	)
	var i Promo
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Amount,
		&i.Comment,
		&i.MaxUses,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPromoActivation = `-- name: CreatePromoActivation :exec
INSERT INTO promo_activations (promo_id, user_id) VALUES ($1, $2)
`

type CreatePromoActivationParams struct {
	PromoID int64 `json:"promo_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) CreatePromoActivation(ctx context.Context, arg CreatePromoActivationParams) error {
	_, err := q.db.Exec(ctx, createPromoActivation, arg.PromoID, arg.UserID)
	return err
}

const getPromoByCode = `-- name: GetPromoByCode :one
SELECT p.id, p.code, p.amount, p.comment, p.max_uses, p.created_by, p.created_at, COUNT(pa.id)::int AS activation_count
FROM promos p
LEFT JOIN promo_activations pa ON pa.promo_id = p.id
WHERE UPPER(p.code) = UPPER($1)
GROUP BY p.id
`

type GetPromoByCodeRow struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	Amount          decimal.Decimal    `json:"amount"`
	Comment         string             `json:"comment"`
	MaxUses         int32              `json:"max_uses"`
	CreatedBy       int64              `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActivationCount int32              `json:"activation_count"`
}

func (q *Queries) GetPromoByCode(ctx context.Context, upper interface{}) (GetPromoByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPromoByCode, upper)
	var i GetPromoByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Amount,
		&i.Comment,
		&i.MaxUses,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivationCount,
	)
	return i, err
}
