// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompts.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (title, description, prompt_text, is_official, owner_id, price)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, prompt_text, is_official, owner_id, price, created_at
`

type CreatePromptParams struct {
	Title       string          `json:"title"`
	Description string          `json:"description"`
	PromptText  string          `json:"prompt_text"`
	IsOfficial  bool            `json:"is_official"`
	OwnerID     *int64          `json:"owner_id"`
	Price       decimal.Decimal `json:"price"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.Title,
		arg.Description,
		arg.PromptText,
		arg.IsOfficial,
		arg.OwnerID,
		arg.Price,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PromptText,
		&i.IsOfficial,
		&i.OwnerID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getOfficialPrompts = `-- name: GetOfficialPrompts :many
SELECT id, title, description, prompt_text, is_official, owner_id, price, created_at FROM prompts WHERE is_official = true ORDER BY created_at DESC
`

func (q *Queries) GetOfficialPrompts(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, getOfficialPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PromptText,
			&i.IsOfficial,
			&i.OwnerID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, title, description, prompt_text, is_official, owner_id, price, created_at FROM prompts WHERE id = $1
`

func (q *Queries) GetPromptByID(ctx context.Context, id int64) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PromptText,
		&i.IsOfficial,
		&i.OwnerID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptsByOwner = `-- name: GetPromptsByOwner :many
SELECT id, title, description, prompt_text, is_official, owner_id, price, created_at FROM prompts WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPromptsByOwner(ctx context.Context, ownerID *int64) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, getPromptsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PromptText,
			&i.IsOfficial,
			&i.OwnerID,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
