// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limits.sql

package sqlc

import (
	"context"
)

const checkAndIncrementRateLimit = `-- name: CheckAndIncrementRateLimit :one
INSERT INTO rate_limits (chat_id, request_count, window_start)
VALUES ($1, 1, NOW())
ON CONFLICT (chat_id)
DO UPDATE SET
    request_count = CASE
        WHEN rate_limits.window_start < NOW() - INTERVAL '1 minute'
        THEN 1
        ELSE rate_limits.request_count + 1
    END,
    window_start = CASE
        WHEN rate_limits.window_start < NOW() - INTERVAL '1 minute'
        THEN NOW()
        ELSE rate_limits.window_start
    END
RETURNING request_count
`

func (q *Queries) CheckAndIncrementRateLimit(ctx context.Context, chatID int64) (int32, error) {
	row := q.db.QueryRow(ctx, checkAndIncrementRateLimit, chatID)
	var request_count int32
	err := row.Scan(&request_count)
	return request_count, err
}

const cleanupStaleRequests = `-- name: CleanupStaleRequests :exec
DELETE FROM active_requests WHERE started_at < NOW() - INTERVAL '3 minutes'
`

func (q *Queries) CleanupStaleRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupStaleRequests)
	return err
}

const removeActiveRequest = `-- name: RemoveActiveRequest :exec
DELETE FROM active_requests WHERE chat_id = $1
`

func (q *Queries) RemoveActiveRequest(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, removeActiveRequest, chatID)
	return err
}

const trySetActiveRequest = `-- name: TrySetActiveRequest :one
INSERT INTO active_requests (chat_id, started_at)
VALUES ($1, NOW())
ON CONFLICT (chat_id) DO NOTHING
RETURNING chat_id
`

func (q *Queries) TrySetActiveRequest(ctx context.Context, chatID int64) (int64, error) {
	row := q.db.QueryRow(ctx, trySetActiveRequest, chatID)
	var chat_id int64
	err := row.Scan(&chat_id)
	return chat_id, err
}
