// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const addMessageFile = `-- name: AddMessageFile :exec
INSERT INTO message_files (message_id, file_type, url, name) VALUES ($1, $2, $3, $4)
`

type AddMessageFileParams struct {
	MessageID int64  `json:"message_id"`
	FileType  string `json:"file_type"`
	Url       string `json:"url"`
	Name      string `json:"name"`
}

func (q *Queries) AddMessageFile(ctx context.Context, arg AddMessageFileParams) error {
	_, err := q.db.Exec(ctx, addMessageFile,
		arg.MessageID,
		arg.FileType,
		arg.Url,
		arg.Name,
	)
	return err
}

const addSessionMessage = `-- name: AddSessionMessage :one
INSERT INTO session_messages (session_id, role, text, images, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, role, text, images, is_system, created_at
`

type AddSessionMessageParams struct {
	SessionID int64    `json:"session_id"`
	Role      string   `json:"role"`
	Text      string   `json:"text"`
	Images    []string `json:"images"`
	IsSystem  bool     `json:"is_system"`
}

func (q *Queries) AddSessionMessage(ctx context.Context, arg AddSessionMessageParams) (SessionMessage, error) {
	row := q.db.QueryRow(ctx, addSessionMessage,
		arg.SessionID,
		arg.Role,
		arg.Text,
		arg.Images,
		arg.IsSystem,
	)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Text,
		&i.Images,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const countSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*) FROM session_messages WHERE session_id = $1
`

func (q *Queries) CountSessionMessages(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByUserID = `-- name: CountSessionsByUserID :one
SELECT COUNT(*) FROM chat_sessions WHERE user_id = $1
`

func (q *Queries) CountSessionsByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions (user_id, model, temperature)
VALUES ($1, $2, $3)
RETURNING id, user_id, model, temperature, created_at, updated_at
`

type CreateSessionParams struct {
	UserID      int64           `json:"user_id"`
	Model       string          `json:"model"`
	Temperature decimal.Decimal `json:"temperature"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Model, arg.Temperature)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM chat_sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteOldestUserSessions = `-- name: DeleteOldestUserSessions :exec
DELETE FROM chat_sessions
WHERE id IN (
    SELECT cs.id FROM chat_sessions cs
    WHERE cs.user_id = $1
    ORDER BY cs.updated_at ASC
    LIMIT $2
)
`

type DeleteOldestUserSessionsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) DeleteOldestUserSessions(ctx context.Context, arg DeleteOldestUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOldestUserSessions, arg.UserID, arg.Limit)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM chat_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getFirstSessionMessage = `-- name: GetFirstSessionMessage :one
SELECT id, session_id, role, text, images, is_system, created_at FROM session_messages WHERE session_id = $1 ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstSessionMessage(ctx context.Context, sessionID int64) (SessionMessage, error) {
	row := q.db.QueryRow(ctx, getFirstSessionMessage, sessionID)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Text,
		&i.Images,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageFiles = `-- name: GetMessageFiles :many
SELECT id, message_id, file_type, url, name FROM message_files WHERE message_id = $1
`

func (q *Queries) GetMessageFiles(ctx context.Context, messageID int64) ([]MessageFile, error) {
	rows, err := q.db.Query(ctx, getMessageFiles, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageFile{}
	for rows.Next() {
		var i MessageFile
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileType,
			&i.Url,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, model, temperature, created_at, updated_at FROM chat_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int64) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Model,
		&i.Temperature,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, role, text, images, is_system, created_at FROM session_messages WHERE session_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetSessionMessages(ctx context.Context, sessionID int64) ([]SessionMessage, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Text,
			&i.Images,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, model, temperature, created_at, updated_at FROM chat_sessions WHERE user_id = $1 ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type GetSessionsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSessionsByUserID(ctx context.Context, arg GetSessionsByUserIDParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Model,
			&i.Temperature,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE chat_sessions SET model = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSessionModelParams struct {
	ID    int64  `json:"id"`
	Model string `json:"model"`
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.Exec(ctx, updateSessionModel, arg.ID, arg.Model)
	return err
}

const updateSessionTimestamp = `-- name: UpdateSessionTimestamp :exec
UPDATE chat_sessions SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionTimestamp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateSessionTimestamp, id)
	return err
}
