// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, group_id, amount, tx_type, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, group_id, amount, tx_type, description, created_at
`

type CreateTransactionParams struct {
	UserID      *int64          `json:"user_id"`
	GroupID     *int64          `json:"group_id"`
	Amount      decimal.Decimal `json:"amount"`
	TxType      string          `json:"tx_type"`
	Description string          `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.GroupID,
		arg.Amount,
		arg.TxType,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Amount,
		&i.TxType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupTransactions = `-- name: GetGroupTransactions :many
SELECT id, user_id, group_id, amount, tx_type, description, created_at FROM transactions WHERE group_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetGroupTransactionsParams struct {
	GroupID *int64 `json:"group_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetGroupTransactions(ctx context.Context, arg GetGroupTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getGroupTransactions, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Amount,
			&i.TxType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT id, user_id, group_id, amount, tx_type, description, created_at FROM transactions WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetUserTransactionsParams struct {
	UserID *int64 `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetUserTransactions(ctx context.Context, arg GetUserTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUserTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Amount,
			&i.TxType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
