// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countPremiumUsers = `-- name: CountPremiumUsers :one
SELECT COUNT(*) FROM users WHERE premium_until IS NOT NULL AND premium_until > NOW()
`

func (q *Queries) CountPremiumUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPremiumUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedAfter = `-- name: CountUsersCreatedAfter :one
SELECT COUNT(*) FROM users WHERE created_at >= $1
`

func (q *Queries) CountUsersCreatedAfter(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersCreatedAfter, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_id, first_name, username, referral_code, referred_by_id, is_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, telegram_id, is_admin, first_name, username, balance, referral_code, referral_balance, referred_by_id, premium_until, active_session_id, last_interaction, selected_model, favorite_models, temperature, show_cost, send_user_info, context_enabled, session_timeout_ms, last_skysmart, created_at, updated_at
`

type CreateUserParams struct {
	TelegramID   int64  `json:"telegram_id"`
	FirstName    string `json:"first_name"`
	Username     string `json:"username"`
	ReferralCode string `json:"referral_code"`
	ReferredByID *int64 `json:"referred_by_id"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.FirstName,
		arg.Username,
		arg.ReferralCode,
		arg.ReferredByID,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.IsAdmin,
		&i.FirstName,
		&i.Username,
		&i.Balance,
		&i.ReferralCode,
		&i.ReferralBalance,
		&i.ReferredByID,
		&i.PremiumUntil,
		&i.ActiveSessionID,
		&i.LastInteraction,
		&i.SelectedModel,
		&i.FavoriteModels,
		&i.Temperature,
		&i.ShowCost,
		&i.SendUserInfo,
		&i.ContextEnabled,
		&i.SessionTimeoutMs,
		&i.LastSkysmart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, is_admin, first_name, username, balance, referral_code, referral_balance, referred_by_id, premium_until, active_session_id, last_interaction, selected_model, favorite_models, temperature, show_cost, send_user_info, context_enabled, session_timeout_ms, last_skysmart, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.IsAdmin,
		&i.FirstName,
		&i.Username,
		&i.Balance,
		&i.ReferralCode,
		&i.ReferralBalance,
		&i.ReferredByID,
		&i.PremiumUntil,
		&i.ActiveSessionID,
		&i.LastInteraction,
		&i.SelectedModel,
		&i.FavoriteModels,
		&i.Temperature,
		&i.ShowCost,
		&i.SendUserInfo,
		&i.ContextEnabled,
		&i.SessionTimeoutMs,
		&i.LastSkysmart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByReferralCode = `-- name: GetUserByReferralCode :one
SELECT id, telegram_id, is_admin, first_name, username, balance, referral_code, referral_balance, referred_by_id, premium_until, active_session_id, last_interaction, selected_model, favorite_models, temperature, show_cost, send_user_info, context_enabled, session_timeout_ms, last_skysmart, created_at, updated_at FROM users WHERE referral_code = $1
`

func (q *Queries) GetUserByReferralCode(ctx context.Context, referralCode string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByReferralCode, referralCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.IsAdmin,
		&i.FirstName,
		&i.Username,
		&i.Balance,
		&i.ReferralCode,
		&i.ReferralBalance,
		&i.ReferredByID,
		&i.PremiumUntil,
		&i.ActiveSessionID,
		&i.LastInteraction,
		&i.SelectedModel,
		&i.FavoriteModels,
		&i.Temperature,
		&i.ShowCost,
		&i.SendUserInfo,
		&i.ContextEnabled,
		&i.SessionTimeoutMs,
		&i.LastSkysmart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, is_admin, first_name, username, balance, referral_code, referral_balance, referred_by_id, premium_until, active_session_id, last_interaction, selected_model, favorite_models, temperature, show_cost, send_user_info, context_enabled, session_timeout_ms, last_skysmart, created_at, updated_at FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.IsAdmin,
		&i.FirstName,
		&i.Username,
		&i.Balance,
		&i.ReferralCode,
		&i.ReferralBalance,
		&i.ReferredByID,
		&i.PremiumUntil,
		&i.ActiveSessionID,
		&i.LastInteraction,
		&i.SelectedModel,
		&i.FavoriteModels,
		&i.Temperature,
		&i.ShowCost,
		&i.SendUserInfo,
		&i.ContextEnabled,
		&i.SessionTimeoutMs,
		&i.LastSkysmart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, telegram_id, is_admin, first_name, username, balance, referral_code, referral_balance, referred_by_id, premium_until, active_session_id, last_interaction, selected_model, favorite_models, temperature, show_cost, send_user_info, context_enabled, session_timeout_ms, last_skysmart, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.IsAdmin,
		&i.FirstName,
		&i.Username,
		&i.Balance,
		&i.ReferralCode,
		&i.ReferralBalance,
		&i.ReferredByID,
		&i.PremiumUntil,
		&i.ActiveSessionID,
		&i.LastInteraction,
		&i.SelectedModel,
		&i.FavoriteModels,
		&i.Temperature,
		&i.ShowCost,
		&i.SendUserInfo,
		&i.ContextEnabled,
		&i.SessionTimeoutMs,
		&i.LastSkysmart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserActiveSession = `-- name: SetUserActiveSession :exec
UPDATE users SET active_session_id = $2, updated_at = NOW() WHERE id = $1
`

type SetUserActiveSessionParams struct {
	ID              int64  `json:"id"`
	ActiveSessionID *int64 `json:"active_session_id"`
}

func (q *Queries) SetUserActiveSession(ctx context.Context, arg SetUserActiveSessionParams) error {
	_, err := q.db.Exec(ctx, setUserActiveSession, arg.ID, arg.ActiveSessionID)
	return err
}

const setUserFavoriteModels = `-- name: SetUserFavoriteModels :exec
UPDATE users SET favorite_models = $2, updated_at = NOW() WHERE id = $1
`

type SetUserFavoriteModelsParams struct {
	ID             int64    `json:"id"`
	FavoriteModels []string `json:"favorite_models"`
}

func (q *Queries) SetUserFavoriteModels(ctx context.Context, arg SetUserFavoriteModelsParams) error {
	_, err := q.db.Exec(ctx, setUserFavoriteModels, arg.ID, arg.FavoriteModels)
	return err
}

const setUserIsAdmin = `-- name: SetUserIsAdmin :exec
UPDATE users SET is_admin = $2, updated_at = NOW() WHERE id = $1
`

type SetUserIsAdminParams struct {
	ID      int64 `json:"id"`
	IsAdmin bool  `json:"is_admin"`
}

func (q *Queries) SetUserIsAdmin(ctx context.Context, arg SetUserIsAdminParams) error {
	_, err := q.db.Exec(ctx, setUserIsAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserPremiumUntil = `-- name: SetUserPremiumUntil :exec
UPDATE users SET premium_until = $2, updated_at = NOW() WHERE id = $1
`

type SetUserPremiumUntilParams struct {
	ID           int64              `json:"id"`
	PremiumUntil pgtype.Timestamptz `json:"premium_until"`
}

func (q *Queries) SetUserPremiumUntil(ctx context.Context, arg SetUserPremiumUntilParams) error {
	_, err := q.db.Exec(ctx, setUserPremiumUntil, arg.ID, arg.PremiumUntil)
	return err
}

const setUserSelectedModel = `-- name: SetUserSelectedModel :exec
UPDATE users SET selected_model = $2, updated_at = NOW() WHERE id = $1
`

type SetUserSelectedModelParams struct {
	ID            int64  `json:"id"`
	SelectedModel string `json:"selected_model"`
}

func (q *Queries) SetUserSelectedModel(ctx context.Context, arg SetUserSelectedModelParams) error {
	_, err := q.db.Exec(ctx, setUserSelectedModel, arg.ID, arg.SelectedModel)
	return err
}

const setUserSessionTimeout = `-- name: SetUserSessionTimeout :exec
UPDATE users SET session_timeout_ms = $2, updated_at = NOW() WHERE id = $1
`

type SetUserSessionTimeoutParams struct {
	ID               int64 `json:"id"`
	SessionTimeoutMs int32 `json:"session_timeout_ms"`
}

func (q *Queries) SetUserSessionTimeout(ctx context.Context, arg SetUserSessionTimeoutParams) error {
	_, err := q.db.Exec(ctx, setUserSessionTimeout, arg.ID, arg.SessionTimeoutMs)
	return err
}

const setUserTemperature = `-- name: SetUserTemperature :exec
UPDATE users SET temperature = $2, updated_at = NOW() WHERE id = $1
`

type SetUserTemperatureParams struct {
	ID          int64           `json:"id"`
	Temperature decimal.Decimal `json:"temperature"`
}

func (q *Queries) SetUserTemperature(ctx context.Context, arg SetUserTemperatureParams) error {
	_, err := q.db.Exec(ctx, setUserTemperature, arg.ID, arg.Temperature)
	return err
}

const toggleUserContextEnabled = `-- name: ToggleUserContextEnabled :exec
UPDATE users SET context_enabled = NOT context_enabled, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ToggleUserContextEnabled(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleUserContextEnabled, id)
	return err
}

const toggleUserSendUserInfo = `-- name: ToggleUserSendUserInfo :exec
UPDATE users SET send_user_info = NOT send_user_info, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ToggleUserSendUserInfo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleUserSendUserInfo, id)
	return err
}

const toggleUserShowCost = `-- name: ToggleUserShowCost :exec
UPDATE users SET show_cost = NOT show_cost, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ToggleUserShowCost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, toggleUserShowCost, id)
	return err
}

const updateUserBalance = `-- name: UpdateUserBalance :one
UPDATE users SET balance = balance + $2, updated_at = NOW() WHERE id = $1
RETURNING balance
`

type UpdateUserBalanceParams struct {
	ID      int64           `json:"id"`
	Balance decimal.Decimal `json:"balance"`
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, updateUserBalance, arg.ID, arg.Balance)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const updateUserBalanceWithCheck = `-- name: UpdateUserBalanceWithCheck :one
UPDATE users SET balance = balance + $2, updated_at = NOW()
WHERE id = $1 AND balance + $2 >= 0
RETURNING balance
`

type UpdateUserBalanceWithCheckParams struct {
	ID      int64           `json:"id"`
	Balance decimal.Decimal `json:"balance"`
}

func (q *Queries) UpdateUserBalanceWithCheck(ctx context.Context, arg UpdateUserBalanceWithCheckParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, updateUserBalanceWithCheck, arg.ID, arg.Balance)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE users SET first_name = $2, username = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserInfoParams struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	Username  string `json:"username"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserInfo, arg.ID, arg.FirstName, arg.Username)
	return err
}

const updateUserLastInteraction = `-- name: UpdateUserLastInteraction :exec
UPDATE users SET last_interaction = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastInteraction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastInteraction, id)
	return err
}

const updateUserLastSkysmart = `-- name: UpdateUserLastSkysmart :exec
UPDATE users SET last_skysmart = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastSkysmart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastSkysmart, id)
	return err
}

const updateUserReferralBalance = `-- name: UpdateUserReferralBalance :exec
UPDATE users SET referral_balance = referral_balance + $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserReferralBalanceParams struct {
	ID              int64           `json:"id"`
	ReferralBalance decimal.Decimal `json:"referral_balance"`
}

func (q *Queries) UpdateUserReferralBalance(ctx context.Context, arg UpdateUserReferralBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserReferralBalance, arg.ID, arg.ReferralBalance)
	return err
}
